services:
  postgre:
    image: postgres:${POSTGRES_TAG}
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data
      - /Users/opmartins/labs/transfer_area:/transfer_area #bind mount para transferir arquivos de teste
    networks:
      - kube_news_net

  web-app:
    extends:
      file: kube-news.compose.yaml
      service: kube_news

volumes:
  postgre_docker_vol:
    name: postgre_exemplo_vol
    #external: true

networks:
  kube_news_net:
    driver: bridge
