apiVersion: v1
kind: Pod
metadata:
    name: meupod
spec:
    container:
    - name: web
        image: kubedevio/web-color:blue
        ports:
            - name: http
            containerPort:80
            protocol: TCP